import { config } from 'dotenv'
import { readFile, writeFile } from 'node:fs/promises'
import { decryptReport, sha256 } from '../../lib/evidence/reportCrypto'
config({ path: '.env.local', quiet: true })
const { context } = JSON.parse(decryptReport(await readFile('.demo-captures/premium-xhigh-attempt-2/request.enc', 'utf8'), process.env.REPORT_ENC_KEY!))
type SourcePost = { url: string; postedAt: string; text: string; likes: number; replies: number; reposts: number; views: number }
const posts: SourcePost[] = context.posts.map((p: SourcePost) => ({ url: p.url, postedAt: p.postedAt, text: p.text, likes: p.likes, replies: p.replies, reposts: p.reposts, views: p.views }))
if (posts.some(p => !/^https:\/\/(?:x\.com|twitter\.com)\/[A-Za-z0-9_]+\/status\/\d+$/.test(p.url))) throw new Error('Unexpected source URL; review before exporting')
const sourcebook = { handle: context.actor.handle, displayName: context.actor.displayName, snapshotAt: context.source.scexAsOf, sourceUpdatedAt: context.source.scexUpdatedAt, postCount: posts.length, posts }
const format = (value: number) => value.toLocaleString('en-US')
const sum = (key: 'likes' | 'replies' | 'reposts' | 'views') => posts.reduce((s, p) => s + Number(p[key] || 0), 0)
const escape = (text: string) => text.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;')
const rows = posts.map((p, i) => `<article data-post><div class="post-head"><span>${String(i + 1).padStart(2, '0')} / ${posts.length}</span><time datetime="${escape(p.postedAt)}">${escape(p.postedAt.replace('T', ' ').replace('.000Z', ' UTC'))}</time><a target="_blank" rel="noreferrer" href="${escape(p.url)}">Open source ↗</a></div><details><summary>${escape(p.text.slice(0, 170).replaceAll('\n', ' '))}${p.text.length > 170 ? '…' : ''}</summary><p lang="vi">${escape(p.text)}</p></details><dl><div><dt>Views</dt><dd>${format(p.views || 0)}</dd></div><div><dt>Likes</dt><dd>${format(p.likes || 0)}</dd></div><div><dt>Replies</dt><dd>${format(p.replies || 0)}</dd></div><div><dt>Reposts</dt><dd>${format(p.reposts || 0)}</dd></div></dl></article>`).join('\n')
const encoded = JSON.stringify(sourcebook, null, 2) + '\n'
await writeFile('public/demo/nbaluong-sourcebook.json', encoded)
await writeFile('public/demo/nbaluong-sourcebook.html', `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>nbaluong · Evidence Sourcebook</title><style>
:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:#111013;color:#e9dfcd;font:15px/1.7 system-ui,sans-serif}main{max-width:1120px;margin:auto;padding:clamp(22px,5vw,65px)}h1,h2{font-family:Georgia,serif}h1{font-size:clamp(38px,6vw,64px);line-height:1.1;margin:15px 0}a{color:#d8b779;text-underline-offset:4px}.eyebrow{font-size:11px;letter-spacing:.22em;color:#d1b173}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:30px 0}.metrics div{background:#242019;border:1px solid #615039;border-radius:12px;padding:18px}.metrics b{display:block;font-size:28px;font-family:Georgia,serif;color:#edcc8b}.metrics small,dt{color:#b6a993}.toolbar{position:sticky;top:0;z-index:2;background:#111013ed;padding:16px 0;display:flex;gap:12px;align-items:center;flex-wrap:wrap}input{flex:1;min-width:200px;border:1px solid #695738;border-radius:8px;padding:13px;background:#211d19;color:#eee;font:inherit}button{border:1px solid #695738;border-radius:8px;padding:12px;background:#29221b;color:#e4c897;min-height:44px;cursor:pointer}article{border:1px solid #4c402f;border-radius:12px;padding:22px;margin:18px 0;background:#19171a}article[hidden]{display:none}.post-head{display:flex;gap:16px;flex-wrap:wrap;justify-content:space-between;font-size:12px;color:#b4a78d}summary{cursor:pointer;padding:18px 0;min-height:44px;font-weight:600}details p{white-space:pre-wrap;overflow-wrap:anywhere;border-left:2px solid #9b7949;padding-left:20px;line-height:1.9}dl{display:flex;gap:30px;flex-wrap:wrap;margin-bottom:0}dt{font-size:11px}dd{margin:0;font-size:17px}small{color:#b0a593}footer{font-size:12px;overflow-wrap:anywhere;border-top:1px solid #4c402f;margin-top:30px;padding-top:20px}:focus-visible{outline:2px solid #edcc8b;outline-offset:3px}@media(max-width:600px){.metrics{grid-template-columns:repeat(2,1fr)}article{padding:16px}dl{gap:22px}}
</style></head><body><main><header><span class="eyebrow">KOLOSSEUM / EVIDENCE SOURCEBOOK</span><h1>Every claim starts<br>with a source.</h1><p>nbaluong · @${escape(sourcebook.handle)} · Snapshot ${escape(sourcebook.snapshotAt)}</p><p><small>Original source language is preserved. These are supplied snapshot records, not a fresh independent verification of each live post. Counts are not unique viewers; zero values may be missing-data placeholders.</small></p></header><div class="metrics"><div><b>${posts.length}</b><small>Source posts</small></div><div><b>${format(sum('views'))}</b><small>Recorded views</small></div><div><b>${format(sum('likes'))}</b><small>Recorded likes</small></div><div><b>${format(sum('replies') + sum('reposts'))}</b><small>Replies + reposts</small></div></div><p><a href="nbaluong-sourcebook.json" download>Download source data ↓</a></p><div class="toolbar"><label for="search">Search evidence</label><input id="search" type="search" placeholder="Search posts, handles or dates…"><button id="expand">Expand all posts</button><span id="count" role="status">${posts.length} posts</span></div>${rows}<footer>Source export SHA-256: ${sha256(encoded)}<br>Prepared as the supporting evidence set for a SurfAI research report. No wallet, payment or secret data is included.</footer></main><script>const rows=[...document.querySelectorAll('[data-post]')];document.querySelector('#search').addEventListener('input',e=>{const query=e.target.value.toLowerCase();let count=0;for(const row of rows){row.hidden=!row.textContent.toLowerCase().includes(query);if(!row.hidden)count++}document.querySelector('#count').textContent=count+' posts'});document.querySelector('#expand').addEventListener('click',e=>{const open=e.target.textContent.startsWith('Expand');for(const row of rows)row.querySelector('details').open=open;e.target.textContent=open?'Collapse all posts':'Expand all posts'});</script></body></html>`)
console.log(JSON.stringify({ posts: posts.length, views: sum('views'), likes: sum('likes'), replies: sum('replies'), reposts: sum('reposts'), files: ['public/demo/nbaluong-sourcebook.html', 'public/demo/nbaluong-sourcebook.json'] }))
