// Private local presentation export. Never place this output in public/ or dist/.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { createHash } from 'node:crypto'
const saved=JSON.parse(readFileSync('.demo-captures/agent-live-order.json','utf8')) as {id:string;token:string}
const response=await fetch('https://surfai-api-production.up.railway.app/live/agent/orders/'+saved.id,{headers:{'X-Kolosseum-Agent':saved.token}})
if(!response.ok)throw new Error('Cannot retrieve authenticated order')
const status=await response.json()
const content=status.report?.content as string|undefined
if(content&&createHash('sha256').update(content).digest('hex')!==status.report.contentHash)throw new Error('Report hash mismatch')
const recordedAt=new Date().toISOString()
const replay={recordedAt,handle:status.handle,status:status.status,network:'Surfpool/localnet',priceUsdc:'0.72',creditLimit:120,payment:{verified:status.payment.verified,transaction:status.payment.transaction},report:content?{content,contentHash:status.report.contentHash,snapshotAt:status.report.snapshotAt,sampledPosts:status.report.sampledPosts}:null}
const steps=[['Order prepared','A private medium research order was prepared.'],['HTTP 402','The gateway requires 0.72 test USDC through x402/upto.']]
if(replay.payment.verified){steps.push(['Settlement verified','The backend verified the sandbox transaction, payer, payee and amount.'],['Surf research','One medium report was queued with a 120-credit limit.']);if(content)steps.push(['Report ready','The saved report SHA-256 was verified before export.'])}else steps.push(['Payment rejected','Credential verification failed before settlement. No Surf job was created. Later stages are not recorded as complete.'])
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!))
mkdirSync('.demo-captures/agent-replay',{recursive:true})
writeFileSync('.demo-captures/agent-replay/recording.json',JSON.stringify(replay,null,2))
writeFileSync('.demo-captures/agent-replay/index.html',`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Kolosseum · Recorded agent flow</title><style>
*{box-sizing:border-box}body{margin:0;background:radial-gradient(ellipse at top right,#48301e,#11100f 65%);color:#eee5d5;font:16px/1.7 Arial,sans-serif}main{max-width:1000px;margin:auto;padding:40px 22px}h1,h2{font-family:Georgia,serif}h1{font-size:clamp(38px,6vw,68px);line-height:1.1;margin:36px 0}small{color:#c5ad83}.tag{border:1px solid #87643c;padding:8px 16px;border-radius:30px;display:inline-block}section{border:1px solid #5c4730;border-radius:18px;padding:24px;margin:24px 0;background:#211b16a0}.stats{display:flex;gap:28px;flex-wrap:wrap}.stats strong{display:block;font-size:26px;color:#dfbd7f}button{min-height:46px;padding:10px 22px;border:1px solid #97774c;border-radius:8px;background:#d5b477;color:#25190e;font-weight:bold;margin-right:10px;cursor:pointer}button:focus-visible{outline:3px solid #79cddd;outline-offset:4px}article{white-space:pre-wrap;overflow-wrap:anywhere}code{overflow-wrap:anywhere;font-size:12px}.muted{color:#b8aa93}.rail{display:flex;gap:10px;flex-wrap:wrap}.rail span{padding:8px 12px;border:1px solid #5b4d3b;border-radius:8px}.rail .active{background:#6b482c;color:#ffdf9a}#message{min-height:80px}footer{font-size:13px;color:#b8aa93}</style><main>
<span class="tag">Recorded demo · local copy · no charge</span><h1>An agent pays.<br>Research becomes evidence.</h1><p class="muted">Saved ${escape(recordedAt)} · @${escape(replay.handle)}. Playback sends no API calls or transactions.</p>
<section class="stats"><div><small>PAYMENT CEILING</small><strong>0.72 test USDC</strong></div><div><small>RESEARCH BUDGET</small><strong>120 Surf credits</strong></div><div><small>NETWORK</small><strong>Surfpool sandbox</strong></div></section>
<div class="rail">${steps.map((step,i)=>`<span id="s${i}">${i+1}. ${escape(step[0])}</span>`).join('')}</div><section><h2 id="title"></h2><p id="message" aria-live="polite"></p><button id="play">Play recording</button><button id="next">Next step</button><button id="reset">Reset</button></section>
${replay.payment.transaction?`<details><summary>Sandbox settlement</summary><code>${escape(replay.payment.transaction)}</code></details>`:''}
${replay.report?`<section><h2>Saved Surf report</h2><p>${replay.report.sampledPosts} source posts · ${escape(String(replay.report.snapshotAt))}</p><details><summary>Report SHA-256</summary><code>${escape(replay.report.contentHash)}</code></details><article>${escape(replay.report.content)}</article></section>`:'<p class="muted">No completed report is included in this recording.</p>'}
<footer>The paying agent is the author. The website wallet is an invited reader. NFT minting and transfer controls are separate Solana Devnet actions and are not demonstrated by this recording. This private local copy is not published.</footer></main><script>
const steps=${JSON.stringify(steps).replace(/</g,'\\u003c')};let n=0,timer;const $=id=>document.getElementById(id);function stop(){clearInterval(timer);timer=null;$('play').textContent='Play recording'}function show(){$('title').textContent=steps[n][0];$('message').textContent=steps[n][1];steps.forEach((_,i)=>$('s'+i).className=i<=n?'active':'');$('next').disabled=n===steps.length-1;if(n===steps.length-1)stop()}$('play').onclick=()=>{if(timer)return stop();if(n===steps.length-1)n=0;show();$('play').textContent='Pause';timer=setInterval(()=>{n++;show()},3000)};$('next').onclick=()=>{stop();n=Math.min(n+1,steps.length-1);show()};$('reset').onclick=()=>{stop();n=0;show()};document.addEventListener('visibilitychange',()=>{if(document.hidden)stop()});show();</script></html>`)
console.log({status:replay.status,paymentVerified:replay.payment.verified,reportCharacters:content?.length||0,exported:'.demo-captures/agent-replay/index.html'})
