import { config } from 'dotenv'
import { readFile, writeFile } from 'node:fs/promises'
import { createElement } from 'react'
import { renderToStaticMarkup } from 'react-dom/server'
import { ReportMarkdown } from '../../src/components/ReportMarkdown'
import { decryptReport, sha256 } from '../../lib/evidence/reportCrypto'
import { premiumReport } from '../../lib/payments/reportNft'
config({ path: '.env.local', quiet: true })
const report = await premiumReport()
const attempt = process.argv.find(arg => arg.startsWith('--attempt='))?.split('=')[1] || '3'
if (!/^[1-9]$/.test(attempt)) throw new Error('Invalid attempt')
const directory = attempt === '1' ? '.demo-captures/premium-xhigh' : `.demo-captures/premium-xhigh-attempt-${attempt}`
const request = JSON.parse(decryptReport(await readFile(directory + '/request.enc', 'utf8'), process.env.REPORT_ENC_KEY!))
const posts = request.context.posts as Array<{ url: string; text: string; postedAt: string; likes?: number; replies?: number; reposts?: number; views?: number }>
const sections = report.content.split(/(?=^## )/m).filter((s: string) => s.startsWith('## '))
const reportSources = report.content.split(/^## Sources\s*$/m)[1]?.split(/^## Disclaimer/m)[0] || ''
const missingSources = posts.filter(p => !reportSources.includes(p.url)).map(p => p.url)
const audit = { model: report.model, effort: report.effort, credits: report.credits, creditsSource: report.creditsSource, contentHash: sha256(report.content), words: report.content.split(/\s+/).length, characters: report.content.length, sections: sections.map(s => s.split('\n')[0]), tables: (report.content.match(/^\|?\s*:?-{3,}/gm) || []).length, sampledPosts: posts.length, missingSources, suppliedEngagementTotals: Object.fromEntries(['likes', 'replies', 'reposts', 'views'].map(metric => [metric, posts.reduce((sum, p) => sum + Number(p[metric as keyof typeof p] || 0), 0)])), note: 'Automated structure and coverage checks do not validate every inference. Zero metrics may be source placeholders.' }
await writeFile('public/demo/nbaluong-premium.md', report.content)
const escape = (text: string) => text.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;')
const review = report.editorialReview
const reviewMarkup = review ? `<aside><h2>Source-reviewed edition</h2><p>${escape(review.method)}</p><details><summary>Editorial changes and original report hash</summary><ul>${review.changes.map(change => `<li>${escape(change)}</li>`).join('')}</ul><p>Original Surf content SHA-256: <code>${escape(review.originalContentHash)}</code></p></details></aside>` : ''
const body = reviewMarkup + sections.map((s, i) => `<section id="section-${i}">${renderToStaticMarkup(createElement(ReportMarkdown, { text: s }))}</section>`).join('\n').replaceAll('class="report-md__table-wrap"', 'class="report-md__table-wrap" tabindex="0" role="region" aria-label="Scrollable data table"')
const toc = sections.map((s, i) => `<a href="#section-${i}">${escape(s.split('\n')[0].replace(/^#+\s*/, ''))}</a>`).join('')
await writeFile('public/demo/nbaluong-premium.html', `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>nbaluong · SurfAI Research Dossier</title><style>
:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:#111013;color:#e6ddce;font:16px/1.8 system-ui,sans-serif}main{max-width:1280px;margin:auto;padding:clamp(20px,5vw,72px)}header{border-bottom:1px solid #615038;padding-bottom:30px}h1,h2{font-family:Georgia,serif;line-height:1.25;color:#f4ead9}h1{font-size:clamp(36px,6vw,68px);margin:12px 0}h2{font-size:32px}h3{font-size:22px;color:#d4bd8e}a{color:#d8bb7f;text-underline-offset:4px}small{color:#a99f8e}.eyebrow{font-size:12px;letter-spacing:.2em;color:#d8bb7f}.facts{display:flex;gap:12px;flex-wrap:wrap}.facts span{border:1px solid #55452f;padding:8px 14px;border-radius:6px}nav{display:flex;gap:8px;flex-wrap:wrap;padding:28px 0}nav a{padding:10px 14px;border:1px solid #56462f;border-radius:8px;text-decoration:none;min-height:44px;font-size:13px}section{padding:24px 0;border-bottom:1px solid #42372a;scroll-margin-top:16px}.report-md__table-wrap{overflow-x:auto;border:1px solid #54462f;border-radius:10px;margin:24px 0}.report-md__table{border-collapse:collapse;width:100%;font-size:13px;line-height:1.7}.report-md__table th,.report-md__table td{padding:14px;border:1px solid #40382c;min-width:145px;vertical-align:top;text-align:left}.report-md__table th{background:#28231d;color:#e2c489}.report-md__table tr:nth-child(even){background:#ffffff03}code{overflow-wrap:anywhere;font-size:12px}p,li{overflow-wrap:anywhere}:focus-visible{outline:2px solid #e9c684;outline-offset:3px}.report-md__spacer{height:4px}footer{margin-top:30px;font-size:12px} @media(max-width:640px){body{font-size:14px}h2{font-size:28px}.report-md__table th,.report-md__table td{padding:10px}}@media print{body{background:white;color:black}h1,h2,h3,a{color:black}main{padding:0}nav{display:none}.report-md__table-wrap{overflow:visible}.report-md__table th,.report-md__table td{min-width:0}}
</style></head><body><main><header><span class="eyebrow">KOLOSSEUM / SURFAI RESEARCH DOSSIER</span><h1>Inside the voice.<br>Behind the conviction.</h1><p>nbaluong · @${escape(report.handle)}</p><div class="facts"><span>${escape(report.model)} · ${escape(report.effort)}</span><span>${report.sampledPosts} source posts</span><span>${audit.words.toLocaleString('en-US')} words</span><span>Source ${escape(report.snapshotAt)}</span></div><p><small>Prepared research preview. Viewing this page does not constitute payment or NFT ownership.</small></p><a href="nbaluong-premium.md" download>Download Markdown ↓</a> · <a href="nbaluong-sourcebook.html">Explore the 36-post sourcebook →</a></header><nav aria-label="Report contents">${toc}</nav>${body}<footer>Generated ${escape(report.createdAt)} · ${report.credits} credits (${escape(report.creditsSource)})<br>SHA-256: <code>${report.contentHash}</code></footer></main></body></html>`)
await writeFile(directory + '/quality-audit.json', JSON.stringify(audit, null, 2))
console.log(JSON.stringify(audit, null, 2))
